name: Code quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked --all-extras

      - name: Lint code
        run: uv run ./scripts/lint.sh

      - name: Create coverage directory
        run: mkdir coverage

      - name: Run tests
        run: uv run ./scripts/test.sh --generate-html-report=false --coverage-file=coverage/.coverage.${{ runner.os }}-py${{ matrix.python-version }}

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage
          include-hidden-files: true

  combine-coverage:
    name: Combine coverage
    runs-on: ubuntu-latest
    needs: ["lint-and-test"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: coverage
          merge-multiple: true

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: uv sync --locked --all-extras

      - name: Combine coverage
        run: uv run coverage combine coverage

      - name: Show report summary
        run: uv run coverage report

      - name: Generate report
        run: uv run coverage html --title "Coverage for ${{ github.sha }}"

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: .coverage_html
          include-hidden-files: true
