name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Lint
      uses: devcontainers/ci@v0.3
      with:
        runCmd: poetry run bash ./scripts/lint.sh
