name: Publish release

on:
  release:
    types:
      - created

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: uv sync --locked --no-dev

      - name: Build project
        run: uv build

      - name: Publish to pypi
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
