name: Publish release

on:
  release:
    types:
      - created

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and publish release
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: 3.12
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          poetry_install_options: "--without dev"
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
