name: Publish coverage report

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Lint and test"]
    branches: [main]
    types: 
      - completed

jobs:
  publish-coverage-report:
    name: Publish coverage report
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download coverage report artifact
      uses: dawidd6/action-download-artifact@v7
      with:
        workflow: lint-and-test.yml
        name: coverage-report
        workflow_conclusion: success
        if_no_artifact_found: fail

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'

    - name: Install smokeshow
      run: pip install smokeshow

    - name: Publish coverage report
      run: smokeshow upload coverage-report
      env:
        SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
        SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 90
        SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
