name: Publish release

on:
  release:
    types:
      - created

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: latest

      - name: Install dependencies
        run: poetry install --without dev

      - name: Build project
        run: poetry build

      - name: Configure pypi repository
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/

      - name: Configure pypi token
        run: poetry config pypi-token.testpypi ${{ secrets.PYPI_TOKEN }}

      - name: Publish to pypi
        run: poetry publish --repository=testpypi
